### PR TITLE
(Hopefully) Fixed hotbars not saving on specific maps. Updates Micro map pool to have more diverse gamemodes and replaced unpopular maps.

### PR DESCRIPTION
**Pull request by MysticatLive**

### CODE REVIEW

**Comment by sowhatifimlazy** [comment]
Have these changes been tested on a sandbox server to see if they work? I don't think these changes will fix kits not being editable.

I'd also prefer to have the map rotation changes in a separate pull request, but this will do for now.

**Comment by MysticatLive** [comment]
I was never told a sandbox server existed. Others agreed with me that maps
where there were more than "default" kits broke and all the maps I changed
were the ones that had the issue. I do not appear to be able to make
multiple pull requests (or i just don't understand Git lol)

 Content Creator • Developer • Voice Actor
<https://www.youtube.com/channel/UC9mvRrl9o7rG65ABsGVvDBw>
<https://twitter.com/MysticatLive> <https://www.twitch.tv/mysticatlive>
<https://discord.gg/Mysticat> ***@***.***>

**Comment by sowhatifimlazy** [comment]
When I speak about a sandbox server, I mean setting up your own server and testing the changes you've made so we don't merge things that are broken (ex: bad json formatting, unexpected side effects, etc).

If you're unable to setup your own server, I'll do it for you when I'm next available. :+1:

**Comment by BTKingly** [comment]
Warzone map dev here; I'm not saying to not test, but these changes will work. JSON formatting looks correct too.

**Comment by sowhatifimlazy** [comment]
> Warzone map dev here; I'm not saying to not test, but these changes will work. JSON formatting looks correct too.

Nice to see you here! I went ahead and tested these changes and they do seem to work. Thanks for the contribution @MysticatLive. 👍

**Pull request merged**
